version: '3.4'

services:
  banking:
    image: ${DOCKER_REGISTRY-}banking
    build:
      context: .
      dockerfile: Banking/Dockerfile
    depends_on:
      - supportapi

  supportapi:
    image: ${DOCKER_REGISTRY-}supportapi
    build:
      context: .
      dockerfile: SupportAPI/Dockerfile

  db:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bVhDX2XcgwEatQ6djUNKLm786wguSjpm
      POSTGRES_DB: banking
    ports:
      - 5435:5432