version: "3.8"

services:
  db:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bVhDX2XcgwEatQ6djUNKLm786wguSjpm
      POSTGRES_DB: banking
    ports:
      - 5436:5432
